#!/usr/bin/env bash

if [[ $# -gt 0 ]];then
  if [[ "$1" == "composer" ]]; then
    shift 1
    docker run --rm --interactive --tty --volume $PWD:/app composer "$@"
  elif [[ "$1" == "test" ]]; then
    shift 1
    docker run -it --rm -v "$PWD":/app -w /app php:7.4-cli php vendor/bin/phpunit "$@"
  fi
fi
